applications/blog/urls.py
from django.urls import path
from . import views

app_name="blog_app"

urlpatterns= [
    path('blog/', views.blog, name="blog"),
    path('category/<int:category_id>/', views.category, name="category"),

]

applications/caja/urls.py
#
from django.urls import path
from . import views

app_name = "caja_app"

urlpatterns = [
    path(
        'cierre-caja/index/', 
        views.ReporteCierreCajaView.as_view(),
        name='caja-index',
    ),
    path(
        'cierre-caja/cerrar/', 
        views.ProcesoCerrarCajaView.as_view(),
        name='caja-cerrar',
    ),
]

applications/home/urls.py
from django.urls import path
from . import views

app_name="inicio_app"

urlpatterns = [
    path('', views.HomeView.as_view(), name='inicio'),
    path(
        'panel/admin/', 
        views.PanelAdminView.as_view(),
        name='index-admin',
    ),
    path(
        'panel/admin-reporte/', 
        views.ReporteAdmin.as_view(),
        name='admin-reporte',
    ),
    path(
        'panel/admin-liquidacion/', 
        views.ReporteLiquidacion.as_view(),
        name='admin-liquidacion',
    ),
    path(
        'panel/admin-resumen-ventas/', 
        views.ReporteResumenVentas.as_view(),
        name='admin-resumen_ventas',
    ),
    path(
        'acerca-de/',
        views.about,
        name='acerca-de'
    ),

    path(
        'contacto/',
        views.contact,
        name='contact'
    ),
    
]

applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'users/register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'users/logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'users/update-password/<pk>/', 
        views.UpdatePasswordView.as_view(),
        name='user-update_password',
    ),
    path(
        'users/update/<pk>/', 
        views.UserUpdateView.as_view(),
        name='user-update',
    ),
    path(
        'users/delete/<pk>/', 
        views.UserDeleteView.as_view(),
        name='user-delete',
    ),
    path(
        'users/lista/', 
        views.UserListView.as_view(),
        name='user-lista',
    ),
]

market_rodolfo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.users.urls')),
    path('', include('applications.blog.urls')),
    path('', include('applications.producto.urls')),
    path('', include('applications.venta.urls')),
    path('', include('applications.caja.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>

        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <style>
            html, body {
                height: 100%;
                margin: 0;
            }
            body {
                display: flex;
                flex-direction: column;
            }
            main {
                flex: 1;
            }
        </style>
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column min-vh-100">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-4">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'inicio_app:inicio' %}">Domi's Market</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">

                        <!-- Opciones accesibles para TODOS -->
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase {% if request.resolver_match.url_name == 'inicio' %}active{% endif %}" href="{% url 'inicio_app:inicio' %}">Inicio</a>
                        </li>
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase {% if request.resolver_match.url_name == 'acerca-de' %}active{% endif %}" href="{% url 'inicio_app:acerca-de' %}">Acerca de</a>
                        </li>
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase {% if request.resolver_match.namespace == 'producto_app' %}active{% endif %}" href="{% url 'producto_app:product-list' %}">Productos</a>
                        </li>
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase {% if request.resolver_match.url_name == 'blog' %}active{% endif %}" href="{% url 'blog_app:blog' %}">Blog</a>
                        </li>
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase {% if request.resolver_match.url_name == 'contact' %}active{% endif %}" href="{% url 'inicio_app:contact' %}">Contacto</a>
                        </li>

                        {% if user.is_authenticated %}
                            <!-- Opciones SOLO para usuarios logueados -->
                            <li class="nav-item dropdown px-lg-4">
                                <a class="nav-link dropdown-toggle text-uppercase {% if request.resolver_match.url_name in 'venta-index caja-index' %}active{% endif %}" href="#" id="ventasDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Ventas
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="ventasDropdown">
                                    <li><a class="dropdown-item" href="{% url 'producto_app:producto-lista' %}">Productos</a></li>
                                    <li><a class="dropdown-item" href="{% url 'venta_app:venta-index' %}">Vender</a></li>
                                    <li><a class="dropdown-item" href="{% url 'caja_app:caja-index' %}">Cerrar Caja</a></li>
                                </ul>
                            </li>

                            <li class="nav-item dropdown px-lg-4">
                                <a class="nav-link dropdown-toggle text-uppercase {% if request.resolver_match.url_name in 'index-admin user-lista admin-reporte' %}active{% endif %}" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Administrar
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="adminDropdown">
                                    <li><a class="dropdown-item" href="{% url 'inicio_app:index-admin' %}">Administración</a></li>
                                    <li><a class="dropdown-item" href="{% url 'users_app:user-lista' %}">Usuarios</a></li>
                                    <li><a class="dropdown-item" href="{% url 'inicio_app:admin-reporte' %}">Reportes</a></li>
                                    <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                                </ul>
                            </li>

                            <li class="nav-item px-lg-4">
                                <a class="nav-link text-uppercase" href="{% url 'users_app:user-logout' %}">Salir</a>
                            </li>
                        {% else %}
                            <!-- Opciones SOLO para usuarios no logueados -->
                            <li class="nav-item px-lg-4">
                                <a class="nav-link text-uppercase {% if request.resolver_match.url_name == 'user-login' %}active{% endif %}" href="{% url 'users_app:user-login' %}">Ingresar</a>
                            </li>
                            
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        
        <!-- Bloque opcional para encabezados de página -->
        {% block hero %}{% endblock %}

        <main class="flex-grow-1">
            {% block content %}
            {% endblock %}
        </main>
        
        <!-- Footer-->
        <footer class="py-5 bg-dark text-light">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Domi's Market 2026</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>